name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  ci-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Validar sintaxis HTML
        run: |
          sudo apt-get update && sudo apt-get install -y tidy
          tidy -errors -q html/*.html || true

  deploy:
    runs-on: ubuntu-latest
    needs: ci-check
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 137.184.127.11 >> ~/.ssh/known_hosts

      - name: Conectarse al servidor y hacer git pull
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes alumno@137.184.127.11 "
            cd ~/lemp-sites/marcos_altamirano &&
            git pull origin main
          "

