name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Preparar clave SSH desde el secreto
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 137.184.127.11 >> ~/.ssh/known_hosts

      - name: Probar conexión al servidor
        run: |
          ssh -o StrictHostKeyChecking=yes alumno@137.184.127.11 "echo ' Conexión exitosa desde GitHub Actions'; whoami; date"

